### ISSUE TITLE
52 - My Nutrition - Customise & Swap

### ISSUE THREAD

**Issue by JeremyRolleston** [JeremyRolleston/active8me#52]
This functionality allows the user to swap the allocated meal for another one in the database. 
(NB: In the future this will also automatically update the weekly shopping list - changing ingredients for a changed meal, subtracting ingredients if they update for their own meal etc)

This operates via the swipe functionality on the home screen.
![screen shot 2017-02-27 at 6 47 28 pm](https://cloud.githubusercontent.com/assets/20980200/23358519/3ecef446-fd1d-11e6-8401-4ba47dd4e0bf.png)

<img width="956" alt="screen shot 2017-03-28 at 8 59 08 pm" src="https://cloud.githubusercontent.com/assets/20980200/24406018/6fbf49d2-13f9-11e7-90fe-1f4badecca4f.png">

**Comment by the-konis** [comment]
hi @JeremyRolleston ,

Can you please re upload the images into this GIT ticket?

I will leave this off the AOT untill I can see the images.

Nhan.

**Comment by the-konis** [comment]
HI @JeremyRolleston ,

Just to confirm the logic:

1. Clicking Swap will take us the the new screen.
2. The old item will appear at top until we click the new item.
3. Clicking the new item will replace the old item at top, with rounded circle + orange tick.
4. Clicking "Swap" will process the swap.

Q: What happen if we click "Own meal"? can you describe the logic here?

Nhan.

**Comment by JeremyRolleston** [comment]
Own meal was originally designed because of shopping list integration functionality. This was where if someone had eaten their own meal (eg they ate out at a restaurant or ate another meal) then they would update in the swap function here. This would then update the shopping list by taking things OUT of the shopping list. (Normal swapping of one recipe for another would take the old ingredients out and replace with the new ones). 

We can ignore the own meal functionality for now => therefore ignore the 5th screen
