### ISSUE TITLE
53 - Calories page

### ISSUE THREAD

**Issue by JeremyRolleston** [JeremyRolleston/active8me#53]
The Calories page within My Progress & Tools needs to be completed. 

This page gets linked to from 2 different places - the Calories counter on the home screen and from My Progress & Tools.
![screen shot 2017-02-27 at 5 33 53 pm](https://cloud.githubusercontent.com/assets/20980200/23355976/1b0a14aa-fd13-11e6-9f55-9f9fb8cdc456.png)
<img width="236" alt="screen shot 2017-08-25 at 6 14 16 pm" src="https://user-images.githubusercontent.com/20980200/29710049-532467ba-89c1-11e7-8008-0d3f8f4bb30c.png">

NB: The same as is the case for points on the home screen, the calories circle on the home screen shows how many of the daily calories have been consumed. This will reflect the circle on the calories page. (So if the daily calorie limit is 1500 and the person has consumed 1000 calories, the green bar will be 2/3rds of the way around the circle. If the person has consumed 1600 calories, the circle will go all the way around and be in red for 100 calories). 
<img width="526" alt="screen shot 2017-08-25 at 6 23 49 pm" src="https://user-images.githubusercontent.com/20980200/29710388-a088c720-89c2-11e7-8931-c8cf0e62f281.png">

NB: This page allows the user to manually enter their own calories (consumed ie eaten) or burned ie exercise). 2 scenarios:
A) The user cooks an Active8me recipe and clicks 'DONE'. Then these calories for that meal get added to the total of calories consumed. 
B) The user eats out or eats another meal, but still wants to track their calories so they wish to enter the calories from that meal (which will get added to the existing total). (Please note that we do not have the calculator for calculating how many calories are in the meal - we would want to do this with MyFitnesspal once it becomes open api again).
<For reference only>
<img width="234" alt="screen shot 2017-03-28 at 9 57 35 pm" src="https://cloud.githubusercontent.com/assets/20980200/24408971/97592686-1401-11e7-9217-0ee66387dd2c.png">

NB: On the calories burned this is not just calories expended through exercise (eg the calories from an Active8me workout). It also takes into account someone's BMR (Basal Metabolic Rate). This is a simple equation that can be provided. 2 scenarios:
A) The user completes the Active8me workout and either clicks 'FINISH WORKOUT' for the workout plan or the workout video gets to the end and they get awarded the points. In each case the calories expended that are associated with that workout are added to the total of calories burned. 
B) The user does their own workout, but still wants to track their calories so they wish to enter the calories burned from that workout(which will get added to the existing total). So they manually enter it. (Please note that we do not have the calculator for calculating how many calories are burned in that workout - they need to figure this out. When we have wearable integration this would be automatically calculated through the wearable. 

_NB: Note for Active8me For Future_
On the calories burned / expenditure side we should think about how we can correlate the calories so it takes it from their watch more than just clicking done at the end of the workout. This would be more accurate and help with conversations with insurers.

**Comment by the-konis** [comment]
hi @JeremyRolleston ,

Can you describe the logic for the "Add food" screen?

1. What happen when we click the "Create a Food".
2. What happen when we click the "Quick Add"
3. What happen if we click "Settings"
4. What happen if we click "Multi-add"
5. What happen if we click on the tabs (Recent, Frequent, My Foods, Meals, Recipes)? Please explain if those render the data within the app or from My Fitness Pal?

Nhan.
