### ISSUE TITLE
58 - Insert App analytics

### ISSUE THREAD

**Issue by JeremyRolleston** [JeremyRolleston/active8me#58]
To be discussed. We would like your view on this also. 
What app analytics do we want to measure?
Who do we use? eg mixpanel, google analytics now has app analytics, app annie, appsflyer, elastic.io, fabric.io

Reference:
Consider these options - https://www.techinasia.com/appsflyer-series-c

**Comment by the-konis** [comment]
HI @JeremyRolleston ,

Currently we have 2 app analytics that are default:

1. iOS: https://analytics.itunes.apple.com
2. Android: https://play.google.com/apps/publish. Go to the app "Active8me" Click on Statistics.

Those are having fabulous UI with detailed information. So please confirm if you can use this to save the cost?

Nhan.
