### ISSUE TITLE
59 - Social Sharing / FB login to be inserted

### ISSUE THREAD

**Issue by JeremyRolleston** [JeremyRolleston/active8me#59]
This also relates to Ticket 1 - adding registration via Facebook.
![screen shot 2017-11-22 at 1 33 03 pm](https://user-images.githubusercontent.com/20980200/33111597-f4f61c06-cf89-11e7-946b-0e58be25dd88.png)

This social logon and social sharing were not included in phase 1. So we need to:
1. Settings - Social media accounts are managed ongoing through settings. Need to be able to integrate with various social media accounts here in settings. (We removed this question from registration recently - see previous designs) => If the user integrates successfully then display a tick on the RHS of that social media channel in the registration screen. Also put that user's social media username in brackets on the RHS of the tick (in orange) so the user knows that we are getting the right social media account)

Please note. One user can have 3 or more social media accounts. 
Please note: If the user goes to share and hasn't integrated with that social media platform then it wont show. 
TBC - do we have a message saying "Please integrate your social media account to share your progress". 
![screen shot 2017-11-22 at 1 38 36 pm](https://user-images.githubusercontent.com/20980200/33111867-3199d11a-cf8b-11e7-85af-8514b1171a27.png)

2. This also relates to sharing of any workout, My Nutrition Meal, My Mindset and My Life action - this pop-up screen comes in after the congratulations page once a user clicks done. It allows the user to share their achievement with a photo and a pre-populated message. 
TBC - will we use the standard on the phone or an api where the user selects what medium they share to eg Instagram, Facebook, email etc
NB: You will note that the pop-up screen is different for workout vs nutrition vs mindset
![screen shot 2017-11-22 at 1 30 11 pm](https://user-images.githubusercontent.com/20980200/33111679-494cd010-cf8a-11e7-987c-02952aadf2db.png)
![screen shot 2017-11-22 at 1 30 25 pm](https://user-images.githubusercontent.com/20980200/33111680-49a2234e-cf8a-11e7-99bd-fd045c08bddb.png)
![screen shot 2017-11-22 at 1 30 55 pm](https://user-images.githubusercontent.com/20980200/33111681-49d185d0-cf8a-11e7-9d28-af33b933149b.png)

3. This also relates to sharing of the Before and after photo
![screen shot 2017-11-22 at 1 35 54 pm](https://user-images.githubusercontent.com/20980200/33111638-1c5c36b8-cf8a-11e7-953c-8618c99023bb.png)

4. This also relates to the sharing of the Daily Dose of Inspiration
![screen shot 2017-11-22 at 1 33 47 pm](https://user-images.githubusercontent.com/20980200/33111609-fff81212-cf89-11e7-95a5-da8955772b6d.png)

5. This also relates to the sharing of some pre-program tasks e.g. share commitment
![screen shot 2017-11-22 at 1 44 41 pm](https://user-images.githubusercontent.com/20980200/33111925-7ac5738a-cf8b-11e7-8c61-29acea22b8ed.png)
![screen shot 2017-11-22 at 1 45 31 pm](https://user-images.githubusercontent.com/20980200/33111926-7af6a842-cf8b-11e7-9b0e-8495d2e0d5ee.png)

Designs for the pages once you click share have yet to be designed.

**Comment by the-konis** [comment]
hi @JeremyRolleston ,

When you click share, will all the functions in relevant places has the same FB/Twitter/Instagram type/content? Just unclear on the message that will appear on FB/Twitter/Instagram 

 i.e: Sharing "Your ratings", then what will appear on FB/Twitter/Instagram (message, image?, rating number?)

Nhan.

**Comment by JeremyRolleston** [comment]
A8 to define the pre-defined messages that go into the social media platform
eg "A daily dose of Inspiration from Active8me
+ image of quote
eg "Another Active8me workout completed"

Just to clarify - the share button will just allow for the sharing on social media platforms of a pre-populated message which the user can then add an image / video / their own comment to (or whatever that social media platform natively allows). 

- Share your progress - this is where it would allow the user to add a photo to a predefined message relating to whether they finished a meal or a workout. eg Another healthy Active8me meal finished. (It doesn't share the rating)
- Share your commitment - "The Active8me commitment I am making is this "
- Share to inspire your friends "Active8me's Daily Dose of Inspiration"
- Share Your Nomination - "My Active8me accountability partner nomination is ..."
- Share your image - "My Active8me transformation". This would also share the before and after photo

We will have one share button

**Comment by JeremyRolleston** [comment]
AWS suggested cognito might be good to handle FB login data. But cognito is not yet in Asia. So how do we handle FB login data? 
We could set up a US instance (or another region). Narmeet can talk to Lilian @ AWS to confirm timing and other stuff re cognito
