### ISSUE TITLE
81 - Registration Screen small design changes 

### ISSUE THREAD

**Issue by JeremyRolleston** [JeremyRolleston/active8me#82]
There are some design changes to the registration pages and these have been outlined in the design file. The pdf file outlines the changes for ease and the final .ai file contains all final screen designs to be implemented. 

Changes:
1. First page
- we added a little line above the login button and moved the login button down slightly
- We changed the label on the main orange button as we no longer have a free trial

2. Step 1 - rego details page = Added a background photo to first step.
NB: Please note that in the designs there is social logon inserted there. This is not part of the current task. This will form part of an upcoming task which includes Github 59 where social sharing will get inserted throughout the app). For now this screen can stay as it is, with the addition of the background photo. 
![screen shot 2017-11-21 at 3 54 04 pm](https://user-images.githubusercontent.com/20980200/33060739-3f045eb8-ced4-11e7-92c6-c496bfe2304a.png)

3. Step 2 =  
- Changed intro sentence (Note the use of their first name)
- Changed the exact wording in one of the questions (Choose your program:)
- Added take a selfie (use their camera or library - exactly like we do for Before & After photo in My Progress & Tools)
- Made the select circles bigger
- We have added 2 new program options (Diabetes Prevent' and 'Kickstarter Express'). These are in Umbraco.
- We have added 2 questions on 'Choose your nutrition plan:' and "Choose your regional meal plan preference'. These 2 questions relate to the work we did on tagging recipes and the new algorithm to deliver recipes. 
![screen shot 2017-11-21 at 3 51 11 pm](https://user-images.githubusercontent.com/20980200/33060673-04f70914-ced4-11e7-989f-33425f999e80.png)

3. Step 3 =  
- Removed question/box on address (as no one was filling it in)
- (relates to Github 34) Inserting the ability for someone to select from a pre-defined list of groups (that we load in the back-end CMS and that they can search from dropdown or predictive text search) or to be able to add their own group name (so they can form their own group with friends). 
![screen shot 2017-11-21 at 3 51 32 pm](https://user-images.githubusercontent.com/20980200/33060683-0d5099c2-ced4-11e7-8f16-524fd74eed5f.png)

4. Step 4 = 
- We removed question on (1) social media accounts and (2) accountability partners and added an open question on goals. 
(NB: Note the use of their first name here)
(NB: Please note - this text on goals from the input box needs to get saved. It is able to be access and edited in settings and it will get shown to the user every two weeks when they open the app (as the first thing they see). 
(NB: When we add preferences in settings the user will be able to change how often they see this in settings).
![screen shot 2017-11-24 at 10 21 06 am](https://user-images.githubusercontent.com/20980200/33193090-38aee9fa-d101-11e7-9f8f-4a55e7981ec2.png)
![screen shot 2017-11-24 at 10 21 55 am](https://user-images.githubusercontent.com/20980200/33193114-5a222980-d101-11e7-9d97-f4058603db78.png)

- As per Github 103 the animation will happen once the user clicks finish registration
(NB: note the use of their first name in this animation). 
(NB: this makes sense as the next step is finish registration and animation playing before delivering to home screen). 
![screen shot 2017-11-21 at 3 53 17 pm](https://user-images.githubusercontent.com/20980200/33060716-2a0dfb04-ced4-11e7-9d94-f6c0a3b4020c.png)

Step 5 = on website registration there are small changes on the last page which we are splitting out. (See also Github #94). This last 'Congratulations' page only exists on the website version and it has details on how to download the app and login, plus details for Platinum registrants on getting their DNA test.
------------------------------
IGNORE ALL BELOW (FOR REFERENCE ONLY)

1. On the payment page after you select your program, please put in a heading called "PAYMENT" (This is the same size font and same positioning as "JOIN NOW").
2. I think it is already, but just check if the "Enter your payment details by clicking on the payment below" is the same size font as "Choose the plan that's right for you ..." on the previous page
![img_6281](https://cloud.githubusercontent.com/assets/20980200/22007639/436b7c2e-dcaf-11e6-8b6a-105a4b71ea36.PNG)
<img width="287" alt="screen shot 2017-03-25 at 3 11 02 pm" src="https://cloud.githubusercontent.com/assets/20980200/24320313/dda46e3e-116d-11e7-91e8-53f8daf3fef5.png">

Also is this writing too small when you have it on a small phone
![img_6283](https://cloud.githubusercontent.com/assets/20980200/22007728/160993e6-dcb0-11e6-9da1-7c64df356bec.PNG)

**Comment by the-konis** [comment]
HI @JeremyRolleston ,

In ticket: http://tasks.s60.com.au/browse/AU-190 - Word document. It states that we do not have the Payment in registration flow. And that is what happening now.

So are you effectively saying that we need to bring back the Payment into registration? Or this is for minisite only?

Nhan.

**Comment by JeremyRolleston** [comment]
Yes this is for the mini-site only where it is opt-out and where we take people's payment details up-front during registration.
