### ISSUE TITLE
83 - See All Workout Videos function needs to work

### ISSUE THREAD

**Issue by JeremyRolleston** [JeremyRolleston/active8me#84]
Currently the app says this function (SEE ALL WORKOUT VIDEOS) is under construction. This workout video page needs to be linked so this button works. 
![workout video](https://cloud.githubusercontent.com/assets/20980200/24234537/dc8ef4e2-0fd3-11e7-90dc-5ee34a2fcc0d.png)

When a user clicks on '+' a pop up appears saying "Saved to favourites"

This SEE ALL WORKOUT VIDEOS function allows a user to select another workout video in place of the one that has been served up (eg they may have a favourite or be injured or feel like doing another workout video).

* If the user reaches this page from the workout video page and selects another workout video on the new screen

- this new video gets delivered in the normal workout video screen) - in place of the previous/original workout that was scheduled via Umbraco. (The user then clicks play to watch it). 

- As per all workout videos the video will go to the congratulations screen afterwards for the awarding of their points. 
(NB: Please note that there should be a condition that says that the awarding of points is only if they haven't already been awarded workout points for that day). We don't want people doing 2-3 workouts a day just to get awarded points. 

* If the user reaches this page via "Resources" then they can still play the video and do the workout. If the user has not done a workout for that day then they are still directed to the congratulations screen and awarded points at the end. (But as per above, if the user has already done a workout for that day (either a workout video or workout plan that has awarded points) then they can do the workout (we can't stop them selecting and playing a video from this section), but they do not get awarded points). 

<img width="960" alt="screen shot 2017-03-28 at 9 08 21 pm" src="https://cloud.githubusercontent.com/assets/20980200/24406366/c9d9a7f4-13fa-11e7-90ea-862b621ad457.png">

In filter, the user can filter the list of workout videos by:
- Duration (multiple option selected) ... 0-10mins, 10-20mins, 20-30mins, 30-40mins, 40-50mins
- Equipment required (multiple options selected) ...Yoga Mat, Chair, Dumbbell, Medicine Ball, Swiss Ball, Resistance Band, Skipping Rope, Barbell
- Workout Video Type (multiple option selected) ... Favourites, Cardio, Toning, Yoga&Core, Pregnancy, Post-Baby, Water, Dance, Celebrity (NB: A field would need to get added into Umbraco for this. It can have multiple fields like for equipment in workout) NB: There is also a dropdown functionality up the top for quick filtering of this workout type.

**Comment by the-konis** [comment]
hi @JeremyRolleston ,

Can you please clarify this: "NB: There is also a dropdown functionality up the top for quick filtering of this workout type."

I think the scenario for this feature is:

1. User select workout video type (multiple selection). There a tick marks on the left of selected items.
2. User then choose items in "FILTER" (for Equipment of Workout length).
3. There is a clear button at the top of "FILTER" popup, next to the "X".
4. Search by name will clear all previous filters.

Nhan.

**Comment by the-konis** [comment]
hi @JeremyRolleston ,

There is an issue with the video watching. Scenario:

1. Today video = A.
2. Tomorrow video = B.
3. User click "See all workout videos"
4. User choose video B as coincident.
5. User see congratulations screen.

Q: 
+ what happen with video A (today) in home?
+ what happen with video B (tomorrow) in home?
Please note that the logics of workout videos is automatic, and we have a set of pre-defined tasks = complicated.

SUGGESTION:
+ We will allow user to watch the workout videos freely, but nothing relate to points, no rewards.

Nhan.

**Comment by JeremyRolleston** [comment]
A user can do 3 actions
1. They can use the LH dropdown to select from the dropdown list. If a user clicks the dropdown menu and selects that option then the selection of videos is automatically filtered to only show that selected workout type
or
2. User can use the filter function and filter by various selections. (If the user selects an option a little tick would appear o the left of the selected item. If they click that item again the tick disappears. We can implement a clear button at the top next to the 'x' 
or
3. The user can search by name in the RH option. This will clear all previous filter.

**Comment by JeremyRolleston** [comment]
A user changing their video workout selection does not have any impact on future pre-defined workouts. (This will be the same logic for when a user changes one meal for another).
