### ISSUE TITLE
87 - Leaderboard to get added to My Progress & Tools

### ISSUE THREAD

**Issue by JeremyRolleston** [JeremyRolleston/active8me#88]
This allows users to compare their points to other users. They can compare by:

- Company eg Apple
- Group that they joined eg Jeremy's group or Apple Sales
- Country eg Singapore
- To all other individuals (this preference can be changed in settings)
- By age group (this is determined by their date of birth entered upon registration. Age groups are 20-30, 30-40,40-50,50-60).

<img width="520" alt="screen shot 2017-03-28 at 9 04 13 pm" src="https://cloud.githubusercontent.com/assets/20980200/24406176/2644076a-13fa-11e7-9420-a4411fe44e4b.png">

Note: This page also allows the Issuing of a challenge. When a user issues a challenge this is the process:
1. They go to a pop-up text box where they enter (A) email address of recipient of challenge (B) their message. This is limited in number of characters. 
2. The recipient (this is matched by email address) then receives a notification that _"First Name Last Name (eg Jeremy Rolleston) has issued a challenge"_. 
3. When the recipient clicks on that notification it goes to a page where there is the challenge message / previous conversation. The recipient can reply in a new text box. 
4. This new message then shows as a notification in the other users notifications. 

<img width="519" alt="screen shot 2017-03-28 at 9 04 21 pm" src="https://cloud.githubusercontent.com/assets/20980200/24406185/2f5aff2a-13fa-11e7-97c9-ced5ca4bb458.png">

Alternatively we just support this challenge via Facebook

**Comment by the-konis** [comment]
hi @JeremyRolleston ,

Just to confirm the logic. In the description we will have a textbox (A) to enter email address. But in the screenshot we do not have this. We also missed the "Send" button.

1. Just to confirm the logic:
A. Click on the name on leaderboard will show the popup, enter message => click "Send".
B. Add in a label "To" with textbox for user to enter the name of recipient, enter the message => click "Send".

2. In the message view we have "camera icon". Just to confirm that clicking the icon will be the same as My Photo - which shows:
+ Camera
+ Library

3. After we select the photo to send in (2), then how will the image display in the conversation?

Nhan.
